name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app

    - name: Build and test
      run: xcodebuild \test \-project HomeTask/HomeTask.xcodeproj \-scheme HomeTask\ -destination 'platform=iOS Simulator,name=iPhone 13'
